# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 03:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0002_auto_20160222_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentialcollege',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='points',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 23, 3, 22, 58, 209282, tzinfo=utc)),
        ),
    ]
