# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 04:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0003_auto_20160223_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='points',
            name='date',
            field=models.DateField(default=datetime.date(2016, 2, 23)),
        ),
    ]
