# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 20:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0008_auto_20160224_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateField(default=datetime.date(2016, 2, 25)),
        ),
        migrations.AlterField(
            model_name='points',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='scores.ResidentialCollege'),
        ),
    ]
